name: Readme resim guncelleme

on:
  schedule:
    
    - cron: '0 */6 * * *'
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  update-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Python kur
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: 'req.txt'
      - name: Bagilmiliklari kur
        run: |
          python -m pip install --upgrade pip
          pip install -r req.txt

      - name: uret
        run: |
          python action.py

      - name: Commit Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chronos: guncelledni"
          file_pattern: "asset.png"